// import 'package:bzoozle/Models/confirmation_model.dart';

// List<Confirmation> confirmationList = [
//   Confirmation(
//     type: "description",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "location",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "openHours",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "setting",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "food",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "wifi",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "entertainment",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "games",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "parking",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "accessibility",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "description",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "location",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "openHours",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "setting",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "food",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "wifi",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "entertainment",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "games",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "parking",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
//   Confirmation(
//     type: "accessibility",
//     uDate: "",
//     uName: "",
//     uLocation: "",
//     uImage: "",
//     cDate: "",
//     cName: "",
//     cLocation: "",
//     cImage: "",
//   ),
// ];
// List<String?> hostNameList =
//     confirmationList.map((confirmation) => confirmation.type).toList();
