import 'package:bzoozle/Models/host_model.dart';

List<Host> hostList = [
  Host(
      hostName: "N/A",
      unitNumber: "",
      addressNumber: "",
      street: "",
      area: "",
      city: "",
      zip: ""),
  Host(
      hostName: "Area15 Complex",
      unitNumber: "",
      addressNumber: "3215",
      street: "S Rancho Dr",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89102"),
  Host(
      hostName: "Aria Casino",
      unitNumber: "",
      addressNumber: "3730",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89158"),
  Host(
      hostName: "AZ Charlie's Boulder Casino",
      unitNumber: "",
      addressNumber: "4575",
      street: "Boulder Hwy",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89121"),
  Host(
      hostName: "AZ Charlie's Decatur Casino",
      unitNumber: "",
      addressNumber: "740",
      street: "S Decatur Blvd",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89107"),
  Host(
      hostName: "Bally's Casino",
      unitNumber: "",
      addressNumber: "3645",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Bellagio Casino",
      unitNumber: "",
      addressNumber: "89109",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Binion's Casino",
      unitNumber: "",
      addressNumber: "128",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Boulder Station Casino",
      unitNumber: "",
      addressNumber: "4111",
      street: "Boulder Hwy",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89121"),
  Host(
      hostName: "Boulevard Mall",
      unitNumber: "",
      addressNumber: "3528",
      street: "S Maryland Pkwy",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89169"),
  Host(
      hostName: "Caesars Palace Casino",
      unitNumber: "",
      addressNumber: "3570",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "California Casino",
      unitNumber: "",
      addressNumber: "12",
      street: "E Ogden Ave",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Casino Royale",
      unitNumber: "",
      addressNumber: "3411",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Centennial Center Mall",
      unitNumber: "",
      addressNumber: "8060",
      street: "W Tropical Pkwy",
      area: "North of Strip",
      city: "Las Vegas",
      zip: "89149"),
  Host(
      hostName: "Circa Casino",
      unitNumber: "",
      addressNumber: "8",
      street: "Fremont Street Experience",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Circus Circus Casino",
      unitNumber: "",
      addressNumber: "2880",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Cosmopolitan Casino",
      unitNumber: "",
      addressNumber: "3708",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Crystals Mall",
      unitNumber: "",
      addressNumber: "3720",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89158"),
  Host(
      hostName: "The Cromwell Casino",
      unitNumber: "",
      addressNumber: "3595",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "The D Casino",
      unitNumber: "",
      addressNumber: "301",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "The District Mall (Resorts World)",
      unitNumber: "",
      addressNumber: "3000",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "The District Mall (Green Valley Ranch)",
      unitNumber: "",
      addressNumber: "2240",
      street: "Village Walk Dr",
      area: "South of Strip",
      city: "Henderson",
      zip: "89052"),
  Host(
      hostName: "Downtown Container Park",
      unitNumber: "",
      addressNumber: "707",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Downtown Grand Casino",
      unitNumber: "",
      addressNumber: "206",
      street: "N 3rd St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Downtown Summerlin Mall",
      unitNumber: "",
      addressNumber: "1980",
      street: "Festival Plaza Dr",
      area: "West of Strip",
      city: "Summerlin",
      zip: "89135"),
  Host(
      hostName: "Eastside Cannery Casino",
      unitNumber: "",
      addressNumber: "5255",
      street: "Boulder Hwy",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89122"),
  Host(
      hostName: "El Cortez Casino",
      unitNumber: "",
      addressNumber: "600",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Ellis Island Casino",
      unitNumber: "",
      addressNumber: "4250",
      street: "Koval Lane",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Encore Casino",
      unitNumber: "",
      addressNumber: "3131",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Excalibur Casino",
      unitNumber: "",
      addressNumber: "3850",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Fashion Show Mall",
      unitNumber: "",
      addressNumber: "3200",
      street: "S Las Vegas Blvd",
      area: "THe Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Flamingo Casino",
      unitNumber: "",
      addressNumber: "3555",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Forum Shops at Caesars",
      unitNumber: "",
      addressNumber: "3500",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Four Queens Casino",
      unitNumber: "",
      addressNumber: "202",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Fremont Casino",
      unitNumber: "",
      addressNumber: "200",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Galleria at Sunset Mall",
      unitNumber: "",
      addressNumber: "1300",
      street: "West Sunset Road",
      area: "East of Strip",
      city: "Henderson",
      zip: "89014"),
  Host(
      hostName: "Gold Coast Casino",
      unitNumber: "",
      addressNumber: "4000",
      street: "W Flamingo Rd",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89103"),
  Host(
      hostName: "Golden Gate Casino",
      unitNumber: "",
      addressNumber: "1",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Golden Nugget Casino",
      unitNumber: "",
      addressNumber: "129",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Grand Canal Shoppes Mall",
      unitNumber: "",
      addressNumber: "3377",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Green Valley Ranch Casino",
      unitNumber: "",
      addressNumber: "2300",
      street: "Paseo Verde Pkwy",
      area: "South of Strip",
      city: "Henderson",
      zip: "89052"),
  Host(
      hostName: "Harrah's Casino",
      unitNumber: "",
      addressNumber: "3475",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Harmon Corner Mall",
      unitNumber: "",
      addressNumber: "3717",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "The Historic Commercial Center",
      unitNumber: "",
      addressNumber: "953",
      street: "East Sahara Avenue",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89104"),
  Host(
      hostName: "Jerry's Nugget Casino",
      unitNumber: "",
      addressNumber: "1821",
      street: "Las Vegas Blvd N",
      area: "North of Strip",
      city: "North Las Vegas",
      zip: "89030"),
  Host(
      hostName: "Linq Promenade",
      unitNumber: "",
      addressNumber: "3545",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Linq Casino",
      unitNumber: "",
      addressNumber: "3535",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Longhorn Casino",
      unitNumber: "",
      addressNumber: "5288",
      street: "Boulder Hwy",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89122,"),
  Host(
      hostName: "Luxor Casino",
      unitNumber: "",
      addressNumber: "3900",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89119"),
  Host(
      hostName: "Main Street Station Casino",
      unitNumber: "",
      addressNumber: "200",
      street: "North Main Street",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "M Resort Casino",
      unitNumber: "",
      addressNumber: "12300",
      street: "S Las Vegas Blvd",
      area: "South of Strip",
      city: "Henderson",
      zip: "89044"),
  Host(
      hostName: "Mandalay Bay Casino",
      unitNumber: "",
      addressNumber: "3950",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89119"),
  Host(
      hostName: "Meadows Mall",
      unitNumber: "",
      addressNumber: "4300",
      street: "Meadows Lane",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89107"),
  Host(
      hostName: "MGM Grand Casino",
      unitNumber: "",
      addressNumber: "3799",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Miracle Mile Shops @ PH",
      unitNumber: "",
      addressNumber: "3663",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Mirage Casino",
      unitNumber: "",
      addressNumber: "3400",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Neonopolis Complex",
      unitNumber: "",
      addressNumber: "450",
      street: "E Fremont St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "New York New York Casino",
      unitNumber: "",
      addressNumber: "3790",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Orleans Casino",
      unitNumber: "",
      addressNumber: "4500",
      street: "W Tropicana Ave",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89103"),
  Host(
      hostName: "OYO Casino",
      unitNumber: "",
      addressNumber: "115",
      street: "E Tropicana Ave",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Palace Station Casino",
      unitNumber: "",
      addressNumber: "2411",
      street: "W Sahara Ave",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89102"),
  Host(
      hostName: "Palazzo Casino",
      unitNumber: "",
      addressNumber: "3325",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Premium Outlets North Mall",
      unitNumber: "",
      addressNumber: "875",
      street: "S Grand Central Pkwy",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89106"),
  Host(
      hostName: "Premium Outlets South Mall",
      unitNumber: "",
      addressNumber: "7400",
      street: "S Las Vegas Blvd",
      area: "South of Strip",
      city: "Las Vegas",
      zip: "89123"),
  Host(
      hostName: "Palms Casino",
      unitNumber: "",
      addressNumber: "4321",
      street: "W Flamingo Rd",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89103"),
  Host(
      hostName: "Paris Casino",
      unitNumber: "",
      addressNumber: "3655",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Park MGM Casino",
      unitNumber: "",
      addressNumber: "3770",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Planet Hollywood Casino",
      unitNumber: "",
      addressNumber: "3667",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Plaza Casino",
      unitNumber: "",
      addressNumber: "1",
      street: "N Main St",
      area: "Downtown",
      city: "Las Vegas",
      zip: "89101"),
  Host(
      hostName: "Rampart Casino",
      unitNumber: "",
      addressNumber: "221",
      street: "N Rampart Blvd",
      area: "West of Strip",
      city: "Summerlin",
      zip: "89145"),
  Host(
      hostName: "Red Rock Casino",
      unitNumber: "",
      addressNumber: "11011",
      street: "W Charleston Blvd",
      area: "West of Strip",
      city: "Summerlin",
      zip: "89135"),
  Host(
      hostName: "Resorts World Casino",
      unitNumber: "",
      addressNumber: "3000",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Rio Casino",
      unitNumber: "",
      addressNumber: "3700",
      street: "W Flamingo Rd",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89103"),
  Host(
      hostName: "Sahara Casino",
      unitNumber: "",
      addressNumber: "2535",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Sam's Town Casino",
      unitNumber: "",
      addressNumber: "5111",
      street: "Boulder Hwy",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89122"),
  Host(
      hostName: "Santa Fe Station Casino",
      unitNumber: "",
      addressNumber: "4949",
      street: "N Rancho Dr",
      area: "North of Strip",
      city: "Las Vegas",
      zip: "89130"),
  Host(
      hostName: "Shoppes at Palazzo Mall",
      unitNumber: "",
      addressNumber: "3327",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Showcase Mall",
      unitNumber: "",
      addressNumber: "3785",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Silver Sevens Casino",
      unitNumber: "",
      addressNumber: "4100",
      street: "Paradise Rd",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89169"),
  Host(
      hostName: "Silverton Casino",
      unitNumber: "",
      addressNumber: "3333",
      street: "Blue Diamond Rd",
      area: "South of Strip",
      city: "Las Vegas",
      zip: "89139"),
  Host(
      hostName: "South Point Casino",
      unitNumber: "",
      addressNumber: "9777",
      street: "S Las Vegas Blvd",
      area: "South of Strip",
      city: "Las Vegas",
      zip: "89183"),
  Host(
      hostName: "Strat Casino",
      unitNumber: "",
      addressNumber: "2000",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89104"),
  Host(
      hostName: "Suncoast Casino",
      unitNumber: "",
      addressNumber: "9090",
      street: "Alta Dr",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89145"),
  Host(
      hostName: "The Shoppes at Mandalay Place",
      unitNumber: "",
      addressNumber: "3930",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89119"),
  Host(
      hostName: "Tivoli Village",
      unitNumber: "",
      addressNumber: "400",
      street: "S Rampart Blvd",
      area: "West of Strip",
      city: "Las Vegas",
      zip: "89145"),
  Host(
      hostName: "Town Square Mall",
      unitNumber: "",
      addressNumber: "6605",
      street: "S Las Vegas Blvd",
      area: "South of Strip",
      city: "Las Vegas",
      zip: "89119"),
  Host(
      hostName: "TI Casino",
      unitNumber: "",
      addressNumber: "3300",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Tropicana Casino",
      unitNumber: "",
      addressNumber: "3801",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Tuscany Casino",
      unitNumber: "",
      addressNumber: "255",
      street: "E Flamingo Rd",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89169"),
  Host(
      hostName: "Venetian Casino",
      unitNumber: "",
      addressNumber: "3355",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Virgin Casino",
      unitNumber: "",
      addressNumber: "4455",
      street: "Paradise Rd",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89169"),
  Host(
      hostName: "Westgate Casino",
      unitNumber: "",
      addressNumber: "3000",
      street: "Paradise Rd",
      area: "East of Strip",
      city: "Las Vegas",
      zip: "89109"),
  Host(
      hostName: "Wynn Casino",
      unitNumber: "",
      addressNumber: "3131",
      street: "S Las Vegas Blvd",
      area: "The Strip",
      city: "Las Vegas",
      zip: "89109"),
];
List<String?> hostNameList = hostList.map((host) => host.hostName).toList();
