List<String> hostBuildingList = [
  "N/A",
  "Area15 Complex",
  "Aria Casino",
  "AZ Charlie's Boulder Casino",
  "AZ Charlie's Decatur Casino",
  "Bally's Casino",
  "Bellagio Casino",
  "Binion's Casino",
  "Boulder Station Casino",
  "Boulevard Mall",
  "Caesars Palace Casino",
  "California Casino",
  "Casino Royale Casino",
  "Circa Casino",
  "Circus Circus Casino",
  "Cosmopolitan Casino",
  "Crystals mall",
  "The Cromwell Casino",
  "The D Casino",
  "The District Mall",
  "Downtown Container Park Complex",
  "Downtown Grand Casino",
  "Downtown Summerlin Mall",
  "Eastside Cannery Casino",
  "El Cortez Casino",
  "Ellis Island Casino",
  "Encore Casino",
  "Excalibur Casino",
  "Fashion Show Mall",
  "Flamingo Casino",
  "Forum Shops at Caesars",
  "Four Queens Casino",
  "Fremont Casino",
  "Galleria Mall",
  "Gold Coast Casino",
  "Golden Gate Casino",
  "Golden Nugget Casino",
  "Grand Canal Shoppes Mall",
  "Grand Canyon Parkway Mall",
  "Green Valley Ranch Casino",
  "Harrah's Casino",
  "Harmon Corner Mall",
  "Linq Casino",
  "Longhorn Casino",
  "Luxor Casino",
  "Main Street Station Casino",
  "M Resort Casino",
  "Mandalay Bay Casino",
  "Meadows Mall",
  "MGM Grand Casino",
  "Miracle Mile Shops @ PH",
  "Mirage Casino",
  "Neonopolis Complex",
  "New York NY Casino",
  "Orleans Casino",
  "OYO Casino",
  "Palace Station Casino",
  "Palazzo Casino",
  "Premium Outlets North Mall",
  "Premium Outlets South Mall",
  "The Palms Casino",
  "Paris Casino",
  "Park MGM Casino",
  "Planet Hollywood Casino",
  "Plaza Casino",
  "Rampart Casino",
  "Red Rock Casino",
  "Resorts World Casino",
  "Rio Casino",
  "Sahara Casino",
  "Sam's Town Casino",
  "Santa Fe Station Casino",
  "Shoppes at Palazzo Mall",
  "Showcase Mall",
  "Silver Sevens Casino",
  "Silverton Casino",
  "Slots-a-Fun Casino",
  "South Point Casino",
  "Strat Casino",
  "Suncoast Casino",
  "Tivoli Village",
  "Town Square Mall",
  "Treasure Island Casino",
  "Tropicana Casino",
  "Tuscany Casino",
  "Venetian Casino",
  "Virgin Casino",
  "Westgate Casino",
  "Wynn Casino",
];
