import 'package:bzoozle/Models/rants_and_raves_model.dart';

List<RantsRaves> rantsRavesList = [
  RantsRaves(
      type: "Rave",
      title: "Beer Pong Winner!",
      category: "Entertainment",
      date: "16 Jun 2022",
      name: "Chip Lewington",
      location: "Long Beach, California, USA",
      content:
          "Awesome night at Blondies. Entered the doubles beer pong tourney (Thursdays at 10pm) with my buddy Steve and we walked away with 300 bucks!",
      strongDisagreeCount: 0,
      disagreeCount: 0,
      agreeCount: 0,
      strongAgreeCount: 0,
      funnyCount: 0,
      cheersCount: 1),
  RantsRaves(
      type: "Rave",
      title: "Bargain Happy Hour",
      category: "Happy hour",
      date: "7 May 2022",
      name: "Jamal Khan",
      location: "San Diego, California, USA",
      content:
          "\$20 to drink as much as I can in 3 hours! In Vegas? Seriously! That's the price of 1 drink everywhere else.  Expect to see me every day Blondies",
      strongDisagreeCount: 0,
      disagreeCount: 0,
      agreeCount: 1,
      strongAgreeCount: 12,
      funnyCount: 16,
      cheersCount: 8),
  RantsRaves(
      type: "Rave",
      title: "Get the chicken tenders",
      category: "Food",
      date: "16 Apr 2022",
      name: "Jackie Short",
      location: "Buffalo, New York, USA",
      content:
          "I'm a chicken connoisseur and I gotta tell ya that these are some of the best chicken tenders You can find.",
      strongDisagreeCount: 1,
      disagreeCount: 0,
      agreeCount: 2,
      strongAgreeCount: 5,
      funnyCount: 4,
      cheersCount: 3),
  RantsRaves(
      type: "Rant",
      title: "LOUD music",
      category: "Entertainment",
      date: "15 Apr 2022",
      name: "Julie Baker",
      location: "Tallahassee, Florida, USA",
      content:
          "We just wanted a quiet bite to eat but the music was so loud that my husband and I, 3ft apart, had to shout at each other.",
      strongDisagreeCount: 0,
      disagreeCount: 4,
      agreeCount: 1,
      strongAgreeCount: 0,
      funnyCount: 3,
      cheersCount: 1),
  RantsRaves(
      type: "Rave",
      title: "BBQ Western Burger",
      category: "Food",
      date: "15 Apr 2022",
      name: "Julie Baker",
      location: "Tallahassee, Florida, USA",
      content:
          "I had the BBQ Western burger and... my oh my!  Cooked to perfection, hot and juicy, oozing with cheese, bacon, onion rings and BBQ sauce, and comes with a ton of fries. So delicious, but be warned, it gets messy!",
      strongDisagreeCount: 0,
      disagreeCount: 0,
      agreeCount: 3,
      strongAgreeCount: 1,
      funnyCount: 7,
      cheersCount: 3),
  RantsRaves(
      type: "Rants",
      title: "Pickpockets in operation",
      category: "Safety & Security",
      date: "9 Apr 2022",
      name: "Shola Bello",
      location: "Guildford, Surrey, UK",
      content:
          "Beware!!! I caught a man trying to get into my bag from behind. He ran off empty handed but if I hadn't turned around at that moment he could have succeeded. Bar staff weren't interested",
      strongDisagreeCount: 3,
      disagreeCount: 4,
      agreeCount: 1,
      strongAgreeCount: 2,
      funnyCount: 0,
      cheersCount: 1),
  RantsRaves(
      type: "Rave",
      title: "Bar Tender Sam",
      category: "Service",
      date: "7 Mar 2022",
      name: "Chris Harris",
      location: "Cork, County Cork, Ireland",
      content:
          "Sam made sure that we were never without a drink and has great banter that kept us there laughing for too long! A real asset to Blondies",
      strongDisagreeCount: 0,
      disagreeCount: 0,
      agreeCount: 1,
      strongAgreeCount: 2,
      funnyCount: 0,
      cheersCount: 1),
];
