List<String> yesNoList = ["Yes", "No"];
List<String> wifiList = ["Free", "Paid", "None"];
List<String> accessibilityList = ["Good", "Average", "Poor"];
List<String> parkingList = ["Free", "Paid", "None"];
List<String> dressCodeList = ["Strict", "Restrictions", "None"];
List<String> coverChargeList = ["Always", "Sometimes", "Never"];
List<String> smokingList = ["Permitted", "Restricted", "Smoke-free"];
List<String> childList = ["Permitted", "Restricted", "No"];
List<String> dogList = ["Permitted", "Restricted", "No"];
